version: 2.1

orbs:
  android: circleci/android@3.1.0

references:
  create_keystore: &create_keystore
    run:
      name: Create keystore.properties
      command: printf 'MARVEL_KEY=%s\nMARVEL_PRIVATE_KEY=%s' \ $MARVEL_KEY $MARVEL_PRIVATE_KEY > keystore.properties

jobs:
  build:
    executor:
      name: android/android_docker
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - android/restore_build_cache
      - android/restore_gradle_cache
      - *create_keystore
      - run:
          name: Build debug APK
          command: |
            ./gradlew :app:assembleDebug
      - android/save_build_cache
      - android/save_gradle_cache
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

  lint:
    executor:
      name: android/android_docker
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - android/restore_build_cache
      - android/restore_gradle_cache
      - *create_keystore
      - run:
          name: Run Android Lint
          command: ./gradlew lint
      - android/save_build_cache
      - android/save_gradle_cache
      - store_artifacts:
          path: app/build/reports
          destination: reports

  ktlint:
    executor:
      name: android/android_docker
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - android/restore_build_cache
      - android/restore_gradle_cache
      - *create_keystore
      - run:
          name: Run ktlint check
          command: ./gradlew ktlintCheck --continue
      - android/save_build_cache
      - android/save_gradle_cache

  detekt:
    executor:
      name: android/android_docker
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - android/restore_build_cache
      - android/restore_gradle_cache
      - *create_keystore
      - run:
          name: Run detekt check
          command: ./gradlew detekt
      - android/save_build_cache
      - android/save_gradle_cache
      - run:
          name: Save detekt reports
          command: |
            mkdir -p ~/detekt-results/detekt/
            find . -type f -regex ".*/build/reports/detekt/.*html" -exec cp {} ~/detekt-results/detekt/ \;
          when: always
      - store_artifacts:
          path: ~/detekt-results/detekt/

  unit_test:
    executor:
      name: android/android_docker
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - android/restore_build_cache
      - android/restore_gradle_cache
      - *create_keystore
      - android/run_tests:
          test_command: ./gradlew jacocoFullTestReport
      - android/save_build_cache
      - android/save_gradle_cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - run:
          name: Upload coverage report to Coveralls
          command: ./gradlew coveralls
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: build/reports
          destination: reports

  android_test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: 2025.03.1
    steps:
      - checkout
      - android/change_java_version:
          java_version: 17
      - *create_keystore
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
          post-emulator-wait-steps:
            - run:
                name: Tap screen
                command: |
                  sleep 30
                  adb shell input keyevent 82
      - android/save_build_cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: build/reports
          destination: reports

workflows:
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - ktlint:
          requires:
            - build
      - detekt:
          requires:
            - build
      - unit_test:
          requires:
            - build